# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cwuniversities', '0001_initial'),
        ('cwusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuniversitydecision',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_university_decisions', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='studentuniversitydecision',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_university_decisions', to='cwuniversities.university'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='cwuniversities.deadlinecategory'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='type_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='cwuniversities.deadlinetype'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cwuniversities.university'),
        ),
        migrations.AddConstraint(
            model_name='studentuniversitydecision',
            constraint=models.UniqueConstraint(fields=('student', 'university', 'deadline'), name='unique_student_university_decision'),
        ),
        migrations.AddConstraint(
            model_name='deadline',
            constraint=models.UniqueConstraint(fields=('university', 'category', 'type_of'), name='unique_deadline'),
        ),
    ]
