# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cwtutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cwresources', '0001_initial'),
        ('cwcounseling', '0001_initial'),
        ('cwtasks', '0002_initial'),
        ('cwusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='recurringcounseloravailability',
            name='counselor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availability', to='cwusers.counselor'),
        ),
        migrations.AddField(
            model_name='counselortimeentry',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='cwusers.counselor'),
        ),
        migrations.AddField(
            model_name='counselortimeentry',
            name='counselor_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_time_entry', to='cwcounseling.counselormeeting'),
        ),
        migrations.AddField(
            model_name='counselortimeentry',
            name='counselor_time_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_time_entries', to='cwcounseling.counselortimecard'),
        ),
        migrations.AddField(
            model_name='counselortimeentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_time_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselortimeentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_time_entries', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='counselortimecard',
            name='admin_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cwusers.administrator'),
        ),
        migrations.AddField(
            model_name='counselortimecard',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwusers.counselor'),
        ),
        migrations.AddField(
            model_name='counselornote',
            name='counselor_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notes', to='cwcounseling.counselormeeting'),
        ),
        migrations.AddField(
            model_name='counselornote',
            name='note_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notes', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='counselormeetingtemplate',
            name='counselor_resources',
            field=models.ManyToManyField(blank=True, related_name='counselor_meeting_template_resources', to='cwresources.resource'),
        ),
        migrations.AddField(
            model_name='counselormeetingtemplate',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_meeting_templates', to='cwcounseling.roadmap'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='counselor_meeting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_meetings', to='cwcounseling.counselormeetingtemplate'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counselor_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_meetings', to='cwcounseling.counseloreventtype'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cwtutoring.location'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='notes_message_completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='+', to='cwtasks.task'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='notes_message_upcoming_tasks',
            field=models.ManyToManyField(blank=True, related_name='+', to='cwtasks.task'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_meetings', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='counselormeeting',
            name='student_resources',
            field=models.ManyToManyField(blank=True, related_name='counselor_meeting_student_resources', to='cwresources.resource'),
        ),
        migrations.AddField(
            model_name='counseloreventtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='cwusers.counselor'),
        ),
        migrations.AddField(
            model_name='counseloravailability',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='cwusers.counselor'),
        ),
        migrations.AddField(
            model_name='counselinghoursgrant',
            name='counseling_package',
            field=models.ForeignKey(blank=True, help_text='(Optional) Counseling Package that was purchased/added resulting in this hours grant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_hours_grants', to='cwcounseling.counselingpackage'),
        ),
        migrations.AddField(
            model_name='counselinghoursgrant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the grant (or purchased package)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counseling_hours_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselinghoursgrant',
            name='student',
            field=models.ForeignKey(help_text='Student hours grant is for', on_delete=django.db.models.deletion.PROTECT, related_name='counseling_hours_grants', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='agendaitemtemplate',
            name='counselor_meeting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_item_templates', to='cwcounseling.counselormeetingtemplate'),
        ),
        migrations.AddField(
            model_name='agendaitemtemplate',
            name='post_meeting_task_templates',
            field=models.ManyToManyField(blank=True, related_name='post_agenda_item_templates', to='cwtasks.tasktemplate'),
        ),
        migrations.AddField(
            model_name='agendaitemtemplate',
            name='pre_meeting_task_templates',
            field=models.ManyToManyField(blank=True, related_name='pre_agenda_item_templates', to='cwtasks.tasktemplate'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='agenda_item_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='cwcounseling.agendaitemtemplate'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='counselor_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='cwcounseling.counselormeeting'),
        ),
    ]
