# Generated by Django 4.2.5 on 2023-09-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwtutoring', '0002_initial'),
        ('cwcounseling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseloravailability',
            name='location',
            field=models.ForeignKey(blank=True, help_text='If availability is in person, the location where user is available in person. If null, then this availability is remote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cwtutoring.location'),
        ),
    ]
