WAITLISTED_THEN_ACCEPTED = "waitlisted_then_accepted"
WAITLISTED_THEN_NOT_ACCEPTED = "waitlisted_then_not_accepted"
WITHDRAWN = "withdrawn"
NOT_REPORTED = "not_reported"
ACCEPTED = "accepted"
ACCEPTED_SPRING = "accepted_spring"
ALTERNATE_ADMISSION = "alternate"
DEFERRED = "deferred"
DEFERRED_THEN_ACCEPTED = "deferred_accepted"
DEFFERED_NOT_ACCEPTED = "deferred_then_not_accepted"
DEFERRED_THEN_WAITLIST = "deferred_then_waitlist"
DEFERRED_THEN_WITHDREW = "deferred_then_withdrew"
GUARANTEED_TRANSFER = "guaranteed_transfer"
NOT_ACCEPTED = "not_accepted"
WAITLISTED = "waitlisted"

ACCEPTANCE_STATUS_CHOICES = (
    (WAITLISTED_THEN_ACCEPTED, WAITLISTED_THEN_ACCEPTED),
    (WAITLISTED_THEN_NOT_ACCEPTED, WAITLISTED_THEN_NOT_ACCEPTED),
    (WITHDRAWN, WITHDRAWN),
    (NOT_REPORTED, NOT_REPORTED),
    (ACCEPTED, ACCEPTED),
    (ACCEPTED_SPRING, ACCEPTED_SPRING),
    (ALTERNATE_ADMISSION, ALTERNATE_ADMISSION),
    (DEFERRED, DEFERRED),
    (DEFERRED_THEN_ACCEPTED, DEFERRED_THEN_ACCEPTED),
    (DEFFERED_NOT_ACCEPTED, DEFFERED_NOT_ACCEPTED),
    (DEFERRED_THEN_WAITLIST, DEFERRED_THEN_WAITLIST),
    (DEFERRED_THEN_WITHDREW, DEFERRED_THEN_WITHDREW),
    (GUARANTEED_TRANSFER, GUARANTEED_TRANSFER),
    (NOT_ACCEPTED, NOT_ACCEPTED),
    (WAITLISTED, WAITLISTED),
)
