# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sntutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sncounseling', '0001_initial'),
        ('sncommon', '0002_initial'),
        ('sntasks', '0002_initial'),
        ('snusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='counseling_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_file_uploads', to='snusers.student'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='counselor_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='sncounseling.counselormeeting'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='diagnostic_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='sntutoring.diagnosticresult'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='sntasks.task'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='sntutoring.testresult'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='tutoring_session_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='sntutoring.tutoringsessionnotes'),
        ),
    ]
