COUNSELOR_MEETING_SCHEDULED = "student_counselor_meeting_confirmed"
COUNSELOR_MEETING_CANCELLED = "student_counselor_meeting_cancelled"
COUNSELOR_COUNSELOR_MEETING_SCHEDULED = "counselor_counselor_meeting_confirmed"
BULLETIN = "bulletin"
TASK_DIGEST = "task_digest"
INVITE = "invite"

CAS_MAGENTO_STUDENT_CREATED = "cas_magento_student_created"
CAP_MAGENTO_STUDENT_CREATED = "cap_magento_student_created"
COUNSELOR_TASK_DIGEST = "counselor_task_digest"
STUDENT_TASK_REMINDER = "student_task_reminder"
INDIVIDUAL_TASK_REMINDER = "task_reminder"

COUNSELOR_FORWARD_STUDENT_MESSAGE = "counselor_forward_student_message"
COUNSELOR_COMPLETED_TASKS = "counselor_completed_tasks"
