# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cwtutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cwcounseling', '0001_initial'),
        ('cwcommon', '0002_initial'),
        ('cwtasks', '0002_initial'),
        ('cwusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='counseling_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_file_uploads', to='cwusers.student'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='counselor_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='cwcounseling.counselormeeting'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='diagnostic_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='cwtutoring.diagnosticresult'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='cwtasks.task'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='cwtutoring.testresult'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='tutoring_session_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='cwtutoring.tutoringsessionnotes'),
        ),
    ]
