# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sntutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('snresources', '0001_initial'),
        ('sntasks', '0001_initial'),
        ('sncounseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_templates', to='sntutoring.diagnostic'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='sntasks.form'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='task_templates', to='snresources.resource'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='sncounseling.roadmap'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='counselor_meeting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sncounseling.counselormeetingtemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='counselor_meetings',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='sncounseling.counselormeeting'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sntutoring.diagnostic'),
        ),
        migrations.AddField(
            model_name='task',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sntasks.form'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(related_name='tasks', to='snresources.resource'),
        ),
    ]
