# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snuniversities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sntasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_university_decisions',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='snuniversities.studentuniversitydecision'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sntasks.tasktemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='sntasks.form'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission', to='sntasks.task'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfieldentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfieldentry',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field_entries', to='sntasks.formfield'),
        ),
        migrations.AddField(
            model_name='formfieldentry',
            name='form_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field_entries', to='sntasks.formsubmission'),
        ),
        migrations.AddField(
            model_name='formfieldentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='sntasks.form'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='snuniversities.university'),
        ),
        migrations.AddField(
            model_name='form',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_form_field'),
        ),
    ]
