# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.conf import settings
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('phone_number_confirmed', models.DateTimeField(blank=True, null=True)),
                ('confirmation_last_sent', models.DateTimeField(blank=True, null=True)),
                ('phone_number_verification_code', models.CharField(blank=True, max_length=5)),
                ('receive_texts', models.BooleanField(default=True)),
                ('receive_emails', models.BooleanField(default=True)),
                ('unsubscribed_email_notifications', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('unsubscribed_text_notifications', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=255)),
                ('is_cc', models.BooleanField(default=False)),
                ('cc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_log_title', models.CharField(blank=True, max_length=255)),
                ('activity_log_description', models.TextField(blank=True)),
                ('emailed', models.DateTimeField(blank=True, null=True)),
                ('texted', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('last_read', models.DateTimeField(blank=True, null=True)),
                ('related_object_pk', models.IntegerField(blank=True, null=True)),
                ('secondary_related_object_pk', models.IntegerField(blank=True, null=True)),
                ('additional_args', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cc_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_notifications', to='snnotifications.notification')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='snnotifications.notificationrecipient')),
                ('related_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('secondary_related_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('send_notification', models.BooleanField(default=True)),
                ('class_years', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, size=None)),
                ('counseling_student_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, default=list, size=None)),
                ('all_class_years', models.BooleanField(default=False)),
                ('all_counseling_student_types', models.BooleanField(default=False)),
                ('cas', models.BooleanField(default=False)),
                ('cap', models.BooleanField(default=False)),
                ('students', models.BooleanField(default=True)),
                ('parents', models.BooleanField(default=True)),
                ('counselors', models.BooleanField(default=False)),
                ('tutors', models.BooleanField(default=False)),
                ('evergreen', models.BooleanField(default=False)),
                ('evergreen_expiration', models.DateTimeField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), blank=True, default=list, size=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bulletins', to=settings.AUTH_USER_MODEL)),
                ('read_notification_recipients', models.ManyToManyField(blank=True, related_name='read_bulletins', to='snnotifications.notificationrecipient')),
                ('visible_to_notification_recipients', models.ManyToManyField(blank=True, related_name='bulletins', to='snnotifications.notificationrecipient')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
