# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('conversation_type', models.CharField(choices=[('co', 'Counselor'), ('tu', 'Tutor'), ('op', 'Operations'), ('ct', 'Counselor-Tutor'), ('ot', 'Other')], default='ot', max_length=2)),
                ('conversation_id', models.CharField(max_length=255)),
                ('conversation_chat_id', models.CharField(max_length=255)),
                ('last_message', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CWPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=18)),
                ('default_tutor_number', models.BooleanField(default=False)),
                ('default_counselor_number', models.BooleanField(default=False)),
                ('default_operations_number', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('deactivated', models.DateTimeField(blank=True, null=True)),
                ('participant_id', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('chat_identifier', models.CharField(blank=True, max_length=255)),
                ('proxy_phone_number', models.CharField(blank=True, max_length=18)),
                ('last_read', models.DateTimeField(auto_now_add=True)),
                ('last_unread_message_notification', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='snmessages.conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
