# Generated by Django 4.2.5 on 2023-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snmessages', '0002_initial'),
        ('snusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='snusers.counselor'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='snusers.parent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='snmessages.snphonenumber'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='snusers.student'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='snusers.tutor'),
        ),
    ]
